apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reusable-app-chart.fullname" . }}
type: Opaque
stringData:
  username: "{{ .Values.secret.username }}"
  password: "{{ .Values.secret.password }}"
