name: CI-CD-Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: flask-app

jobs:

  # Stage 1: Unit Tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt
      - run: pytest


  # Stage 2: Security Scan
  security:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          severity: HIGH,CRITICAL
          exit-code: '1'


  # Stage 3: Docker Build
  build:
    needs: security
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t flask-app:${{ github.sha }} .


  # Stage 4: Push to ECR
  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image
        run: |
          ACCOUNT=${{ secrets.AWS_ACCOUNT_ID }}

          docker build -t flask-app:${{ github.sha }} .

          docker tag flask-app:${{ github.sha }} \
          $ACCOUNT.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/flask-app:${{ github.sha }}

          docker push \
          $ACCOUNT.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/flask-app:${{ github.sha }}

  gitops:
    needs: push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: username/gitops-repo
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Update Manifest
        run: |
          sed -i \
          "s|image:.*|image:${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/flask-app:${{ github.sha }}|" \
          manifests/deployment.yaml

      - name: Commit Changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -m "Update image"
          git push
